// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cblvoxlibzrxokowufod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNibHZveGxpYnpyeG9rb3d1Zm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTkwMDMsImV4cCI6MjA3MTc3NTAwM30.HSiQImr2TWKUBznrNVgykKVibvU-c3JOUq_JONtJ1MI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});